Update README.md
coq-community/awesome-coq pull request #23
Opened 2021-08-13 05:59 UTC by gares

2021-08-13 09:02 UTC, palmskog requested changes
I think this description is way too generic. Please try to squeeze "λProlog" in there somewhere to differentiate from other (tactic) languages.

2021-08-15 06:20 UTC, gares commented on README.md
> +- [Coq-Elpi](https://github.com/LPCIC/coq-elpi) - Extension language to implement commands and tactics.
```suggestion
- [Coq-Elpi](https://github.com/LPCIC/coq-elpi) - Extension framework based on λProlog providing an extensive set of API to implement commands and tactics.
```

2021-08-15 06:21 UTC, gares commented
better?

2021-08-15 06:39 UTC, palmskog approved these changes

2021-08-15 06:40 UTC, merged

2021-08-15 14:52 UTC, gares commented
thanks